version: '3.8'
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  backend:
    build: ./backend
    container_name: api_backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/server
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: client_frontend
    ports:
      - "3000:30000"
    volumes:
      - ./frontend:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  data:
  logs: